[tool.poetry]
name = "marcadores-cli"
version = "0.0.3"
description = "This project is a CLI that allows you to check live scoreboards from www.flashscore through your prefered terminal"
authors = ["diadesdepela@gmail.com"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
click = "^8.1.6"
rich = "^13.7.1"
requests = "^2.32.5"
requests-html = "^0.10.0"
beautifulsoup4 = {url = "https://www.crummy.com/software/BeautifulSoup/bs4/download/4.14/beautifulsoup4-4.14.2.tar.gz"}
selenium = "^4.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
